---
name: FFmpeg Build

on:
 push: null
 workflow_dispatch:
   inputs:
     NDK_VERSION:
       description: Android NDK
       required: true
       default: r28

jobs:
 build:
   runs-on: ubuntu-latest
   env:
     NDK_VERSION: ${{ github.event.inputs.NDK_VERSION || 'r27c' }}
   steps:
     - uses: actions/checkout@v4

     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: '17'

     - name: Setup Android SDK
       uses: android-actions/setup-android@v3

     - name: Download NDK
       run: |
         curl -L "https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip" -o ndk.zip
         unzip -q ndk.zip
         echo "ANDROID_NDK_ROOT=$PWD/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

     - name: Build FFmpeg
       run: |
         ./android.sh -d \
           --enable-android-media-codec \
           --enable-android-zlib \
           --disable-arm-v7a

     - name: Upload Build Logs
       if: failure()
       uses: actions/upload-artifact@v4
       with:
         name: build-logs
         path: build.log

     - name: Upload FFmpeg AAR
       if: success()
       uses: actions/upload-artifact@v4
       with:
         name: ffmpeg-kit
         path: prebuilt/bundle-android-aar/ffmpeg-kit/ffmpeg-kit.aar
